FROM nvidia_ros:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
 
# Install Git
RUN apt-get update && apt-get install -y git
 
# Create a Catkin workspace and clone TurtleBot3 repos
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p /turtlebot3_ws/src \
 && cd /turtlebot3_ws/src \
 && catkin_init_workspace \
 && git clone -b noetic-devel https://github.com/ROBOTIS-GIT/turtlebot3.git \
 && git clone -b noetic-devel https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git \
 && git clone -b noetic-devel https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git
# RUN echo "export TURTLEBOT3_MODEL=burger" >> ~/.bashrc
 
RUN apt install -y build-essential

# Build the Catkin workspace and ensure it's sourced
RUN source /opt/ros/noetic/setup.bash \
 && cd turtlebot3_ws \
 && catkin_make
RUN echo "source /turtlebot3_ws/devel/setup.bash" >> ~/.bashrc
 
RUN source /opt/ros/noetic/setup.bash \
  && cd /turtlebot3_ws/src  \
  && git clone https://github.com/ROBOTIS-GIT/ros_tutorials.git  \
  && cd /turtlebot3_ws \
  && catkin_make

RUN apt install -y vim bear

# Set the working folder at startup
WORKDIR /turtlebot3_ws

COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
